In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
up1 = files.upload()
up2 = files.upload()

Saving OulierRemoved_All_Parameter_Data.csv to OulierRemoved_All_Parameter_Data.csv

Saving Faulty_Data.csv to Faulty_Data.csv

In [ ]:
df = pd.read_csv('OulierRemoved_All_Parameter_Data.csv')
dff = pd.read_csv('Faulty_Data.csv')

In [ ]:
df

,CHAMBER_EXT_TEMP,CHAMBER_OUTLET_TEMP,CHAMBER_TEMP,CHAMBER_VACCUM,CONCT1TEMP,CONCT2TEMP,COOLING_TEMP,CYCLON_VACCUM,FBD_COOLING_TEMP,FBD_HOT_AIR_TEMP,...,FEED_PUMP_FLOW,HIGH_PRESSURE_PUMP,INLET_CHILDWTR_TEMP,PRE_HEATING_TEMP,RECYCLE_PRESSURE,RECYCLE_TEMP,TOP_HOT_AIR_TEMP,SUPPY_FAN_SPEED,EXHAUST_FANSPEED,MOISTURE_CONTENT
0,87.170013,91.512009,185.358002,-11.091100,27.267996,48.242001,58.432003,190.816147,18.522007,91.699997,...,997.5103,140.744430,2.516002,54.174004,0.440748,51.225998,187.10202,1119,1206,3.41
1,86.300003,90.699997,185.300003,-11.091100,27.500000,48.299999,58.200001,186.874191,18.000000,91.699997,...,1012.8790,143.904022,2.400000,54.000000,0.423000,51.400002,186.00000,1136,1210,3.45
2,86.000000,90.400002,185.500000,-11.091100,28.000000,48.400002,58.799999,189.948120,18.100000,92.599998,...,1019.7670,149.351486,2.400000,53.900002,0.427000,51.599998,186.10001,1164,1147,3.06
3,85.000000,89.699997,185.899994,-11.091100,28.299999,48.400002,58.799999,186.485077,17.700001,91.699997,...,1041.7120,154.150452,2.400000,52.799999,0.418100,51.200001,186.70000,1156,1196,3.46
4,85.500000,90.500000,185.699997,-11.091100,28.799999,48.599998,57.900002,202.762650,17.500000,92.400002,...,1062.4900,154.474701,2.400000,51.299999,0.433900,51.900002,186.39999,1142,1197,3.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11779,86.699997,91.599998,183.699997,-10.661484,33.900002,50.900002,53.200001,179.442276,20.900000,92.599998,...,1023.2680,186.186768,5.800000,55.900002,0.428000,52.700001,186.10001,1120,1227,3.11
11780,86.800003,91.300003,182.800003,-9.319069,30.900000,50.799999,53.099998,178.158234,21.299999,92.400002,...,1030.1560,187.159531,4.900000,55.400002,0.407200,52.900002,183.89999,1166,1143,3.34
11781,86.800003,91.099998,184.000000,-11.815826,29.400000,56.599998,53.400002,181.621277,21.600000,92.500000,...,1020.9340,185.862518,7.300000,55.200001,0.450700,52.599998,186.20000,1139,1162,3.37
11782,85.900002,89.800003,182.600006,-14.254219,30.700001,50.000000,53.900002,191.232162,21.400000,92.400002,...,985.2140,190.045395,4.059600,57.500000,0.420100,52.900002,183.80000,1155,1153,3.01
11783,85.542239,90.452079,183.800003,-12.263298,30.200001,34.200001,53.900002,190.207520,19.010000,91.900002,...,1005.4800,179.474701,4.059600,53.685000,0.424610,52.799999,186.00000,1143,1248,3.18

In [ ]:
dff.columns

Index(['TOP_HOT_AIR_TEMP', 'Faulty_TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP',
       'Faulty_CHAMBER_EXT_TEMP', 'CHAMBER_OUTLET_TEMP',
       'Faulty_CHAMBER_OUTLET_TEMP', 'FEED_PUMP_FLOW',
       'Faulty_FEED_PUMP_FLOW'],
      dtype='object')

In [ ]:
df = df[['TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP','CHAMBER_OUTLET_TEMP', 'FEED_PUMP_FLOW']]

In [ ]:
df_final = pd.DataFrame(columns = df.columns)

Index(['TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP', 'CHAMBER_OUTLET_TEMP',
       'FEED_PUMP_FLOW', 'Faulty_TOP_HOT_AIR_TEMP', 'Faulty_CHAMBER_EXT_TEMP',
       'Faulty_CHAMBER_OUTLET_TEMP', 'Faulty_FEED_PUMP_FLOW'],
      dtype='object')

In [ ]:
ff = dff.sample(n = 2500, replace = True)

In [ ]:
faulty_top = ff[['Faulty_TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP', 'CHAMBER_OUTLET_TEMP', 'FEED_PUMP_FLOW']]

In [ ]:
faulty_exit = ff[['TOP_HOT_AIR_TEMP', 'Faulty_CHAMBER_EXT_TEMP', 'CHAMBER_OUTLET_TEMP', 'FEED_PUMP_FLOW']]

In [ ]:
faulty_outlet = ff[['TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP', 'Faulty_CHAMBER_OUTLET_TEMP', 'FEED_PUMP_FLOW']]

In [ ]:
faulty_feed = ff[['TOP_HOT_AIR_TEMP', 'CHAMBER_EXT_TEMP', 'CHAMBER_OUTLET_TEMP', 'Faulty_FEED_PUMP_FLOW']]

In [ ]:
faulty_top.rename(columns = {'Faulty_TOP_HOT_AIR_TEMP': 'TOP_HOT_AIR_TEMP'}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
faulty_exit.rename(columns = {'Faulty_CHAMBER_EXT_TEMP': 'CHAMBER_EXT_TEMP'}, inplace = True)
faulty_outlet.rename(columns = {'Faulty_CHAMBER_OUTLET_TEMP': 'CHAMBER_OUTLET_TEMP'}, inplace = True)
faulty_feed.rename(columns = {'Faulty_FEED_PUMP_FLOW': 'FEED_PUMP_FLOW'}, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
faulty_top['target'] = np.ones(len(faulty_top.TOP_HOT_AIR_TEMP)).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
faulty_top

,TOP_HOT_AIR_TEMP,CHAMBER_EXT_TEMP,CHAMBER_OUTLET_TEMP,FEED_PUMP_FLOW,target
3017,200.30000,85.300003,90.699997,1008.2100,1
2932,199.60001,83.599998,88.500000,993.2685,1
819,201.20000,85.099998,89.500000,1109.7660,1
3278,198.60001,82.699997,87.099998,1005.8750,1
2034,198.70000,83.500000,88.199997,1062.4900,1
...,...,...,...,...,...
4406,203.70000,85.542239,90.452079,1005.4800,1
4717,201.50000,83.500000,88.199997,1075.0970,1
2534,199.10001,84.000000,88.800003,1046.2650,1
686,198.00000,85.900002,91.000000,981.7120,1
18,201.00000,84.800003,90.099998,1103.9300,1

In [ ]:
faulty_feed['target'] = 4*np.ones(len(faulty_top.TOP_HOT_AIR_TEMP)).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
faulty_outlet['target'] = 3*np.ones(len(faulty_top.TOP_HOT_AIR_TEMP)).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
faulty_exit['target'] = 2*np.ones(len(faulty_top.TOP_HOT_AIR_TEMP)).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_final = df_final.append(faulty_top)
df_final = df_final.append(faulty_exit)
df_final = df_final.append(faulty_outlet)
df_final = df_final.append(faulty_feed)

In [ ]:
df_final = df_final.append(df)

In [ ]:
df_final['target'] = df_final['target'].fillna(int(0))

In [ ]:
df_final.target = df_final.target.astype(int)

In [ ]:
df_final

,TOP_HOT_AIR_TEMP,CHAMBER_EXT_TEMP,CHAMBER_OUTLET_TEMP,FEED_PUMP_FLOW,target
3017,200.30000,85.300003,90.699997,1008.2100,1
2932,199.60001,83.599998,88.500000,993.2685,1
819,201.20000,85.099998,89.500000,1109.7660,1
3278,198.60001,82.699997,87.099998,1005.8750,1
2034,198.70000,83.500000,88.199997,1062.4900,1
...,...,...,...,...,...
11779,186.10001,86.699997,91.599998,1023.2680,0
11780,183.89999,86.800003,91.300003,1030.1560,0
11781,186.20000,86.800003,91.099998,1020.9340,0
11782,183.80000,85.900002,89.800003,985.2140,0
11783,186.00000,85.542239,90.452079,1005.4800,0

In [ ]:
df_final.sample(frac = 1)

,TOP_HOT_AIR_TEMP,CHAMBER_EXT_TEMP,CHAMBER_OUTLET_TEMP,FEED_PUMP_FLOW,target
4932,183.39999,57.300003,87.099998,996.6537,2
11561,185.00000,87.500000,91.800003,974.8249,0
5002,182.50000,59.400002,88.800003,1007.0430,2
195,198.50000,85.800003,90.500000,1019.7670,1
5557,183.30000,84.500000,89.699997,993.2685,0
...,...,...,...,...,...
294,184.80000,87.900002,93.500000,802.4900,4
2032,185.30000,83.400002,88.300003,1056.6540,0
5011,184.10001,84.699997,90.000000,1002.4900,0
3967,185.10001,85.300003,90.500000,987.4319,0
3228,202.10001,84.699997,89.800003,1102.8790,1

In [ ]:
df_final = df_final.sample(frac = 1)

In [ ]:
df = df.append(df_final)

In [ ]:
df.sample(frac = 1)

       TOP_HOT_AIR_TEMP  CHAMBER_EXT_TEMP  CHAMBER_OUTLET_TEMP  FEED_PUMP_FLOW
4             186.39999         85.500000            90.500000       1062.4900
3080          198.39999         85.400002            89.699997        964.4358
8058          186.10001         86.300003            91.400002        987.4319
6712          187.80000         87.400002            92.099998       1001.3230
1415          183.70000         86.000000            91.099998        998.9883
...                 ...               ...                  ...             ...
3742          187.39999         84.199997            69.500000       1063.6580
10952         185.39999         85.599998            90.199997       1037.0430
10819         187.20000         87.000000            91.500000        994.4358
5043          184.30000         84.400002            89.699997       1000.1560
2052          186.39999         89.099998            73.900002        978.2101

[21784 rows x 4 columns]

In [ ]:
df.to_csv('All_Included.csv')

In [ ]:
files.download('All_Included.csv')

In [ ]:
df_final.to_csv('Final_Shuffle.csv')

In [ ]:
files.download('Final_Shuffle.csv')